def close_splash():
    """
    Attempts to close Splash Screen for PyQT5 .exe application generated by PyInstaller.\n
    If script is .py file than it does nothing.
    """
    try:
        import pyi_splash
        pyi_splash.close()
    except:
        pass